#!/bin/bash

# Originally written by Ralf Kistner <ralf@embarkmobile.com>, but placed in the public domain

set +e

echo "======================================="
echo "Custom Android Wait For Emulator Script"
echo "======================================="

bootanim=""
laststatus=""
dateStart=$(date +"%s")
dateLast=$dateStart
failcounter=0

until [[ "$bootanim" =~ "stopped" ]]; do
   bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
   
   dateNow=$(date +"%s")
   diff=$(($dateNow-$dateStart))
#   echo "$bootanim, in wait $(($diff / 60)):$(($diff % 60))"

   if [[ "$bootanim" =~ "$laststatus" ]]; then
      diff=$(($dateNow-$dateLast))
      echo -ne "..$diff"
   else
      echo -ne "..update arrieved"\\r
      diff=$(($dateNow-$dateStart))
      echo "new status: $bootanim, total in wait $(($diff / 60)):$(($diff % 60))"
      dateLast=$dateNow
   fi
   
   if [[ "$bootanim" =~ "not found" ]]; then
      let "failcounter += 1"
      if [[ $failcounter -gt 15 ]]; then
        echo "Failed to start emulator"
        exit 1
      fi
   fi
   
   laststatus=$bootanim
   sleep 1
done

echo "======================================="
echo "Android Wait For Emulator Script: Done!"
echo "======================================="
